# https://github.com/Siogop/psr-read-text/blob/main/serverless.yml

service: detect-text

provider:
  name: aws
  runtime: go1.x

  environment:
    Bucket: !Ref Storage
    Table: !Ref Table
    Region: eu-west-1

  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectText"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource:
        - !GetAtt Table.Arn
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref": "Storage"
              - "/*"
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref": "Storage"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        {
          "Fn::Join":
            ["", ["arn:aws:s3:::", { "Ref": "ServerlessDeploymentBucket" }]],
        }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref": "ServerlessDeploymentBucket"
            - "/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  getTextInImage:
    handler: bin/getTextInImage
    events:
      - http:
          path: gettext
          method: post
          cors: true
  uploadImage:
    handler: bin/uploadImage
    events:
      - http:
          path: uploadimage
          method: post
  imageCreated:
    handler: bin/imageCreated
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 2
          arn:
            Fn::GetAtt:
              - Queue
              - Arn
resources:
  Resources:
    Storage:
      Type: AWS::S3::Bucket
      Properties:
        NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:*
              Queue: !GetAtt Queue.Arn
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 120
    QueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref Queue
        PolicyDocument:
          Id: "SQSPolicy"
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "s3.amazonaws.com"
              Action: "sqs:SendMessage"
              Resource: !GetAtt Queue.Arn
